all:
  children:
    master:
      hosts:
        ########: {} # master host IP or hostname
    workers:
      hosts:
        ########: {} # worker-1 IP or hostname
        ########: {} # worker-2 IP or hostname
        ########: {} # worker-3 IP or hostname
